armor_detector_node_cpp:
  ros__parameters:
    detector:
      backend: "yolo"  # traditional / yolo
      target_color: "RED"

      traditional:
        preprocess:
          gray_threshold: 100
          color_threshold: 100
        light:
          min_contours_area: 30
          min_contours_ratio: 0.06
          max_contours_ratio: 0.5
        armor:
          max_angle_diff: 15.0
          min_length_ratio: 0.7
          min_x_diff_ratio: 0.75
          max_y_diff_ratio: 1.0
          max_distance_ratio: 0.8
          min_distance_ratio: 0.1
        number:
          model_path: "model/number_cnn.onnx"
          threshold: 0.5

      yolo:
        model_path: "model/robot_0526.onnx"
        device: "CPU"
        input_size: 640
        score_threshold: 0.65
        nms_threshold: 0.45
        min_confidence: 0.65
        max_raw_candidates: 100
        use_roi: false
        roi:
          x: 0
          y: 0
          width: -1
          height: -1

    debug:
      show: true
      rosbag_control: true
      rosbag_player_node: "/rosbag2_player"
      detect_stage_1: false
      detect_stage_2: false
      detect_stage_3: false
      detect_stage_4: false
      pose: true
      result: true
      stats_interval: 50

    playback:
      mode: "realtime"
      max_frames: 0
      exit_on_complete: false
