armor_detector_node_cpp:
  ros__parameters:
    # 目标颜色
    target_color: "BLUE"

    # 预处理
    gray_threshold: 100
    color_threshold: 100

    # 灯条
    min_contours_area: 30
    min_contours_ratio: 0.06
    max_contours_ratio: 0.5

    # Debug
    debug:
      show: true
      rosbag_control: true
      rosbag_player_node: "/rosbag2_player"
      preprocess: false
      lights: true
      armor_match: false
      classification: false
      pose: false
      stats_interval: 50
